backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Sayfalar"
    folder: "/"
    create: true
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "İçerik", name: "body", widget: "markdown"}
      - {label: "Resim", name: "image", widget: "image"}
