backend:
  name: git-gateway
  branch: main # GitHub'daki ana dalın adı

media_folder: "src/img" # Resimlerin yükleneceği yer
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kapak Görseli", name: "image", widget: "image" }
      - { label: "Kategori", name: "category", widget: "string" }
      - { label: "Özet Metin", name: "excerpt", widget: "text" }
      - { label: "İçerik", name: "body", widget: "markdown" }